### ISSUE TITLE
Unable to open GUI on first run

### ISSUE THREAD

**Issue by rbtylee** [coreymwamba/estonta#1]
The command estonta -ag exits without opening a yad dialog on first run until an event has been created (Folder ~/.local/share/ics is empty). ONe has to either create an event or have a presumably proper file in ~/.local/share/ics

**Comment by coreymwamba** [comment]
I will try to fix this soon, thank you for letting me know.

**Comment by coreymwamba** [comment]
I believe this is fixed now. On first run, a folder is created and the calendar appears.
